version: '3.8'

services:
  info-golang:
    build: ./
    env_file:
      - .env 
    ports:
      - 8081:8081
    networks:
      - info-net
      - app-net

networks:
  info-net:
    driver: bridge
  app-net:
    external: true
