version: '3.8'

services:
  db:
    restart: always
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
    ports:
      - 5432:5432
    networks:
      - net

  tracker-golang:
    build: ./
    env_file:
      - .env 
    command: ["./scripts/wait-for-postgres.sh", "db", "./tracker-golang"]
    depends_on: 
      - db
    ports:
      - 8080:8080
    networks:
      - net

networks:
  net:
    driver: bridge