version: '3.8'

services:
  tracker-app:
    build: ./
    env_file:
      - .env 
    ports:
      - 8080:8080
    networks:
      - tracker-app-net
      - app-net

networks:
  tracker-app-net:
    driver: bridge
  app-net:
    external: true
